#%RAML 1.0
---
title: Books API
baseUri: https://someweb.site/{version}
version: 1.0

/users:
    /authors:
        /{authorName}: 
    /books:
        get:
            queryParameters:
                author:
                publicationYear:
                rating:
                isbn:
        post:
        put:
        /{bookTitle}:
            get:
                queryParameters:
                    author:
                        displayName: Author
                        type: string
                        description: An author's full name
                        example: Mark Twain
                        required: false
                    publicationYear:
                        displayName": Publication Year
                        type: Number
                        description: The year the book was published
                        example: 1984
                        required: false
                    rating:
                        displayName: Rating
                        type: number
                        description: The rating of the book
                        example: 3.55
                        required: false
                    isbn:
                        displayName: ISBN
                        type: string
                        minLength: 10
                        example: 0321736079
            put:
                queryParameters:
                    accessToken:
                        displayName: Access Token
                        type: string
                        description: Token giving your permission to make a call
                        required: true
            delete:
            /author:
                get:
            /publisher:
                get: