#%RAML 1.0
---
title: Books API
baseUri: https://someweb.site/{version}
version: 1.0

/users:
    /authors:
        /{authorName}: 
    /books:
        get:
            queryParameters:
                author:
                publicationYear:
                rating:
                isbn:
        post:
        put:
        /{bookTitle}:
            get:
                queryParameters:
                    author:
                    publicationYear:
                    rating:
                    isbn:
            put:
                queryParameters:
                    accessToken:
            delete:
            /author:
                get:
            /publisher:
                get: