#%RAML 1.0
---
title: Books API
baseUri: https://someweb.site/{version}
version: 1.0

/users:
    /authors:
        /{authorName}: 
    /books:
        get:
            queryParameters:
                author:
                publicationYear:
                rating:
                isbn:
        post:
        put:
        /{bookTitle}:
            get:
                description: Retrieve a specific book title
                responses:
                    200:
                        body:
                            application/json:
                                example: | 
                                {
                                    "data": {
                                        "id": "ed1e651de51d5e1d5e51e51de515e",
                                        "title": "The Catcher in the Rye",
                                        "description": null,
                                        "datetime": "2015-04-15T00:00:00.000Z",
                                        "genre": "Classic",
                                        "author": "J.D. Salinger",
                                        "link": "https://someweb.site/books/the_catcher_in_the_rye",
                                    },
                                    "success": true,
                                    "status": 200
                                }
                queryParameters:
                    author:
                        displayName: Author
                        type: string
                        description: An author's full name
                        example: Mark Twain
                        required: false
                    publicationYear:
                        displayName": Publication Year
                        type: Number
                        description: The year the book was published
                        example: 1984
                        required: false
                    rating:
                        displayName: Rating
                        type: number
                        description: The rating of the book
                        example: 3.55
                        required: false
                    isbn:
                        displayName: ISBN
                        type: string
                        minLength: 10
                        example: 0321736079
            put:
                queryParameters:
                    accessToken:
                        displayName: Access Token
                        type: string
                        description: Token giving your permission to make a call
                        required: true
            delete:
            /author:
                get:
            /publisher:
                get: