#%RAML 1.0
---
title: Jukebox API
baseUri: https://someweb.site/{version}
version: 1.0

/songs:
    get:
    post:
    /{songId}:
        get:
        /file-content:
            get:
            post:
    /artists:
        get:
        post:
        /{artistId}:
            get:
            /albums:
                get:
    /albums:
        get:
        post:
        /{albumId}:
            get:
            /songs:
                get: 